[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7F7F7F"
blue = "#5C5CFF"
cyan = "#00FFFF"
green = "#00FF00"
magenta = "#FF00FF"
red = "#FF0000"
white = "#FFFFFF"
yellow = "#FFFF00"

[colors.normal]
black = "#000000"
blue = "#0000EE"
cyan = "#00CDCD"
green = "#00CD00"
magenta = "#CD00CD"
red = "#CD0000"
white = "#E5E5E5"
yellow = "#CDCD00"

[colors.primary]
background = "#000000"
foreground = "#D0CFCC"

[colors.selection]
background = "#052A2C"
text = "#FFFFFF"

[cursor.style]
blinking = "on"
shape = "Block"

[font]
size = 10

[font.bold]
family = "Inconsolata Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Inconsolata Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Inconsolata Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control"

# [schemes.darcula.bright]
# black = "#7F7F7F"
# blue = "#5C5CFF"
# cyan = "#00FFFF"
# green = "#00FF00"
# magenta = "#FF00FF"
# red = "#FF0000"
# white = "#FFFFFF"
# yellow = "#FFFF00"
#
# [schemes.darcula.normal]
# black = "#000000"
# blue = "#0000EE"
# cyan = "#00CDCD"
# green = "#00CD00"
# magenta = "#CD00CD"
# red = "#CD0000"
# white = "#E5E5E5"
# yellow = "#CDCD00"
#
# [schemes.darcula.primary]
# background = "#000000"
# foreground = "#D0CFCC"
#
# [schemes.darcula.selection]
# background = "#052A2C"
# text = "#FFFFFF"

[scrolling]
history = 8192
multiplier = 3

[selection]
save_to_clipboard = false

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
