general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = true
}

background {
    monitor =
    # Use a screenshot of your current desktop as the background
    path = screenshot
    # Blur it heavily so you can read the text
    blur_passes = 2
    blur_size = 5
    color = rgba(0, 0, 0, 0.5)
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    
    # Text colors
    font_color = rgb(255, 136, 0) # Orange Text
    placeholder_text = <span color="##808080">Input Password...</span> # Grey placeholder

    # Colors
    outer_color = rgb(255, 136, 0) # Orange Ring
    inner_color = rgb(10, 10, 10)  # Almost Black background
    check_color = rgb(255, 200, 0) # Yellowish when checking
    fail_color = rgb(255, 0, 0)    # Red on fail
    
    fade_on_empty = false
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    # Orange Time
    color = rgba(255, 136, 0, 1.0)
    font_size = 80
    font_family = Noto Sans Bold
    position = 0, 100
    halign = center
    valign = center
}
