general {
    # Lock the screen immediately if I call "loginctl lock-session"
    lock_cmd = pidof hyprlock || hyprlock
    # Lock the screen BEFORE the system goes to sleep/suspend
    before_sleep_cmd = loginctl lock-session
    # Turn the screen back on when I touch the mouse
    after_sleep_cmd = hyprctl dispatch dpms on
}


# Lock the screen after 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Turn off monitor after 11 minutes (save battery/power)
listener {
    timeout = 660
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend PC after 15 minutes
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
